<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="WebForm1.aspx.cs" Inherits="ModeloDeEnlace.WebForm1" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
</head>
<body>
    <form id="form1" runat="server">
        <div>
            <asp:GridView ID="gvProfes" runat="server" AutoGenerateColumns="false"
                ItemType="ModeloDeEnlace.ModeloDeDatos.Profesor"
                DataKeyNames="IdProfesor"
                SelectMethod="ObtenerProfesores"
                UpdateMethod="ModificarProfesores"
                DeleteMethod="BorrarProfesores"
                AutoGenerateEditButton="true"
                AutoGenerateDeleteButton="true">
                <Columns>
                    <asp:BoundField DataField="nombre" HeaderText="Nombre" />
                    <asp:BoundField DataField="apellidos" HeaderText="Apellidos" />
                </Columns>
            </asp:GridView>
        </div>

        <br />
        <br />
        <asp:FormView ID="FormView1" runat="server"
            ItemType="ModeloDeEnlace.ModeloDeDatos.Profesor"
            DefaultMode="Insert"
            InsertMethod="InsertarProfesor">
            <InsertItemTemplate>
                Nombre:
            <asp:TextBox ID="txtNombre" runat="server" Text="<%#: BindItem.Nombre %>"></asp:TextBox>
                Apellidos: 
            <asp:TextBox ID="txtApellidos" runat="server" Text="<%#: BindItem.Apellidos %>"></asp:TextBox>
                <asp:Button ID="btnInsertar" runat="server" Text="Insertar" CommandName="Insert" />
            </InsertItemTemplate>
        </asp:FormView>

        <asp:ValidationSummary ID="ValidationSummary1" runat="server" ShowModelStateErrors="true" ForeColor="Red" />
    </form>
</body>
</html>
